### PR TITLE
Add unit tests with mocha

### PR DESCRIPTION
**Pull request by ingomueller-net**
This PR should be added on top of pull request #26.

### CODE REVIEW

**Comment by linuxbandit** [comment]
Then why don't you merge it in the branch of the PR you refer to? This way
it will be part of the same PR

**Comment by ingomueller-net** [comment]
I don't know, it's your call. You should merge in my PRs, no? If you accept all changes, then just merge in this PR and I'll close the others...

**Comment by linuxbandit** [comment]
Sorry for the late answer, I meant to say that maybe if it has another PR as requirement it should be still part of the same PR (i.e. changeset)?

**Comment by ingomueller-net** [comment]
Yes, that's what I thought as well. I just learned how I should have done it: update the same branch I created the PR from (see [this post](http://stackoverflow.com/questions/7947322/preferred-github-workflow-for-updating-a-pull-request-after-code-review)).

So, any comments or requests for change before you can merge?

**Pull request closed without merging**
