### PR TITLE
Adopt best practices of open source projects for quality assurance

### PR DESCRIPTION
**Pull request by ingomueller-net**
This pull requests supersedes PRs #24, #25, #26, #28, and #29.
### gjslint

This adds more linter tasks using [gjslint](https://developers.google.com/closure/utilities/docs/linter_howto).

I applied most improvements suggested by the tool, but long lines should still be broken into shorter ones. I'll leave that task to you, @serviceman ;) Also I deactivated complaints about missing documentation. Having documentation would be great though! Since I am not too sure whether we want the format of documentation that gjslint expects, I currently deactivated this check.
### jsonlint

Check json files for validity.
### Mocha

Run unit tests (better: unit test stubs) with mocha (similar to [this tutorial](http://webapplog.com/tdd/)).
### Coveralls

We should have unit tests and collect how much of our code they cover. With [coveralls](https://coveralls.io/github/ingomueller-net/oms-core), we can display the percentage nicely in the README on Github.
### David

Checks whether all dependencies are up-to-date, i.e., whether we use the latest version of them.

### CODE REVIEW

**Comment by ingomueller-net** [comment]
Indeed, if I push new commits to a branch from which I created a pull request before, the pull request gets updated. This new PR should now avoid all confusions.

@serviceman, I am still waiting for any comments on the commits themselves.

**Comment by linuxbandit** [comment]
I am about to read them

One thing about the line length, I don't see any problem in having them that way (I even checked with vim and they visualise nice). Can't we just raise the length warning?

**Comment by linuxbandit** [comment]
okay, I will merge it in after you send another commit with the badges changed to the upstream repository.

Also please let me know about that other server thing

**Comment by ingomueller-net** [comment]
The maximum length of code lines (just as other style properties) can be discussed. I think it is good to have _some_ maximum. 80 is often used because some terminals have this as their default length (my windows terminal is one of them). Other people argue that with 80 characters, they only use 20% of their 30" screen :P 120 characters is often a compromise.

**Comment by linuxbandit** [comment]
That could be better, also because I don't see any reasons for using a windows terminal to _visualise_ the files! I do programming on vim in console, sometimes, but I doubt windows users will issue any command different than "vagrant <>" on the console

**Comment by ingomueller-net** [comment]
Looks like the line length in gjslint [cannot be changed](https://groups.google.com/forum/#!topic/closure-linter-discuss/CdPdKjJ4pNs). So it's all or nothing for us.

BTW, the [javascript guide](http://google.github.io/styleguide/javascriptguide.xml) of google has no explanation about why it's 80 for them, but the [cpp guide](http://google.github.io/styleguide/cppguide.html#Line_Length) has.

**Comment by ingomueller-net** [comment]
OK, I think I addressed all your concerns and I am quite happy with the result. Good for merging from my side.

**Pull request merged**
