### PR TITLE
Added logging feature using bunyan (supersedes #21)

### PR DESCRIPTION
**Pull request by stebenve86**
I have created a new PR with the dev branch as the target for the merge, sorry for the mess...

### CODE REVIEW

**Comment by linuxbandit** [comment]
no mess, don't worry

**Comment by linuxbandit** [comment]
I have waited to integrate this because @ingomueller-net 's changeset is bigger and I think it is better to have yours on top of his (less things to change)

alternatively I didn't understand quite fully the awesomeness of PRs and I complicated the problem in my mind :)

**Comment by ingomueller-net** [comment]
Yes, I think what you suggest is a good idea. It will help me some work. I can help with the rebasing of #27 to avoid extra work for @stebenve86.

**Comment by ingomueller-net** [comment]
I rebased this PR, see PR #34.

**Pull request closed without merging**
